---
title: 'Assignment 4: Task 2'
author: "Alicia Canales"
date: "2023-03-16"
output: 
  html_document:
    code_folding: hide
---

```{r setup,include=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE, warning=FALSE)
```

```{r}
library(tidyverse)
library(tidyr)
library(here)
library(lubridate)
library(tsibble)
library(feasts)
library(slider)
library(fable)
library(broom)
library(patchwork)
```

*Wrangling Data Area*
```{r}
fish <- read_csv(here('data', 'willamette_fish_passage.csv')) %>% 
 janitor::clean_names()

# making this a timeseries dataset with selected columns and replacing na's with 0
fish_data <- fish %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  select(c('date', 'coho', 'jack_coho', 'steelhead','temp_c')) %>% 
  replace(is.na(.), 0)

fish_ts <- fish_data %>% 
  as_tsibble(key = NULL, index = date)

fish_longer_ts <- fish_ts %>% 
  pivot_longer("coho":"steelhead",
               names_to = "species",
               values_to = "count")

fish_month <- fish_ts %>% 
  index_by(yr_mo = ~yearmonth(.)) %>% 
  summarize(mean_monthly_temp = mean(temp_c))

## for tab 3 
fish_t3 <- fish_data %>% 
  pivot_longer("coho":"steelhead",
               names_to = "species",
               values_to = "count") %>% 
  select(-temp_c)

```

### Quarterly Results {.tabset}

#### Original time Series
```{r}
## making a subset for each species then going to use patchwork to put them all together

# coho
coho_ts<- fish_longer_ts %>%
  filter(species == 'coho')

p_1 <- ggplot(data=coho_ts, aes(x=date, y=count)) +
  geom_line() +
  theme_minimal() +
  labs(title = 'Coho', x = 'Date', y = 'Total Count')

# jack_coho
jack_ts<- fish_longer_ts %>%
  filter(species == 'jack_coho')

p_2 <- ggplot(data=jack_ts, aes(x=date, y=count)) +
  geom_line() +
  theme_minimal() +
  labs(title = 'Jack Coho', x = 'Date', y = 'Total Count')

# steelhead
steelhead_ts<- fish_longer_ts %>%
  filter(species == 'steelhead')

p_3 <- ggplot(data=steelhead_ts, aes(x=date, y=count)) +
  geom_line() +
  theme_minimal() +
  labs(title = 'Steelhead', x = 'Date', y = 'Total count')

# patchwork plot

p_1 + p_2 + p_3 +
  plot_layout(ncol = 1, tag_level = 'new', guides = 'collect') +
  plot_annotation(title = 'Coho, Jack Coho, and Steelhead Salmon Counts',
    caption = 'Figure 1. Time series of Coho, Jack Coho, and Steelhead counts on the Willamette fish ladder between 2001 and 2010.',
    theme = theme(plot.title = element_text(size = 16)))


```


#### Seasonsplots
```{r}
coho <- fish_ts %>% 
  select(date, coho, temp_c) %>% 
  index_by(yr_mo = ~yearmonth(.)) %>% 
  summarize(coho_avg = mean(coho))

j_coho <- fish_ts %>% 
  select(date, jack_coho, temp_c) %>% 
  index_by(yr_mo = ~yearmonth(.)) %>% 
  summarize(jcoho_avg = mean(jack_coho))

steelhead <- fish_ts %>% 
  select(date, steelhead, temp_c) %>% 
  index_by(yr_mo = ~yearmonth(.)) %>% 
  summarize(steel_avg = mean(steelhead))


p1 <- gg_season(coho, y = coho_avg)+
  theme_minimal() +
  labs(x = 'Month', y = 'Average Count', title = 'Coho')

p2 <- gg_season(j_coho, y = jcoho_avg)+
  theme_minimal()+
  labs(x = 'Month', y = 'Average Count', title = 'Jack Coho')

p3 <- gg_season(steelhead, y = steel_avg)+
  theme_minimal()+
  labs(x = 'Month', y = 'Average Count', title = 'Steelhead')

p1 + p2 + p3 + 
  plot_layout(ncol = 1, tag_level = 'new', guides = 'collect') +
  plot_annotation(title = 'Coho, Jack Coho, and Steelhead Salmon Annual population numbers',
    caption = 'Figure 1. Displays Coho, Jack Coho, and Steelhead Salmon annual population numbers from 2001 to 2010.',
    theme = theme(plot.title = element_text(size = 16)))

```




#### Annual Counts by species
```{r}
tab3_annual <- fish_t3 %>% 
  mutate(year = as.Date(as.character(date),format = "%Y")) %>%
  group_by(year, species) %>% 
  summarize(annual_total = sum(count))

ggplot(data = tab3_annual, aes(x = year, y = annual_total)) +
  geom_line(aes(color=species)) +
  theme_minimal() +
  scale_x_date(date_labels = "%Y") +
  scale_color_manual(values = c('#355c7d', '#c06c84', '#f8b195'), 
                     labels=c('Coho Salmon',
                               'Jack Coho Salmon',
                               'Steelhead Salmon'))+
  labs(title = 'Annual Counts for Salmon species from 2000 to 2010',
    x = 'Year',
    y = 'Total Annual Count', color = 'Species')

  


```




